### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by porjo** [adamroyle/ing-au-login#4]
Firstly, thanks so much for this! How can I buy you a beer? 😁  I've been waiting for ING to provide an API for this (Openbanking) but won't be holding my breath waiting for that to arrive any time soon. 

I thought it might be useful to provide a Dockerfile. I managed to get it working with this: https://github.com/porjo/ing-au-login/blob/dockerfile/Dockerfile

That still requires any additional dependencies to be added manually. e.g `yarn add axios`

**Comment by adamroyle** [comment]
Glad it helped you out! This library was designed to be used as a dependency to a separate project, so I'm not sure if makes sense adding a Dockerfile to this repo, as it would make sense to add it to your project instead.

**Comment by porjo** [comment]
OK, no problem.

**Comment by rickysullivan** [comment]
Beer payment remains unresolved.

**Comment by adamroyle** [comment]
Do I need to open a pull request?

![Pull Request](https://s3.ap-southeast-2.amazonaws.com/www.hospitalitymagazine.com.au/wp-content/uploads/20201015101803/The-Pour.jpg)

**Comment by rickysullivan** [comment]
POST package to NZ.
